name: CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3

      - name: Apply Prisma migration
        env:
          DATABASE_URL: "postgres://${{ secrets.NEON_USER }}:${{ secrets.NEON_PASS }}@ep-winter-mud-418148.eu-central-1.aws.neon.tech/lisseborg?connect_timeout=10"
        run: npx prisma migrate deploy
